# traefik.toml
################################################################
# 全局配置文件
################################################################

# 设置超时的时间（以秒为单位）
# 在热更新期间给还在活动中的请求来完成当前任务的超时时间
#
# 可选
# 默认: 10
#
# graceTimeOut = 10

# 开启调试模式
#
# 可选
# 默认: false
#
# debug = true

# 定期检查是否有新版本产生
#
# 可选
# 默认: true
#
# checkNewVersion = false

# Traefik 日志文件
# 如果没有定义, 日志文件输出到 stdout
#
# 可选
#
traefikLogsFile = "log/traefik.log"

# 日志文件路径
#
# 可选
#
accessLogsFile = "log/access.log"

# 日志等级
#
# 可选
# 默认: "ERROR"
# 接受以下值，按照严重程度排序: "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
# 日志等级在配置值或配置值以上的信息将被日志记录。
#
# logLevel = "ERROR"

# 后端节流持续时间：在应用新配置之前，提供者的2个事件之间的最短持续时间（以秒为单位）
# 如果在短时间内发送多个事件，它可以避免不必要的重新加载。
#
# 可选
# 默认: "2"
#
# ProvidersThrottleDuration = "5"

# 为每个host控制最大空闲连接（keep-alive）。如果设置为0，那么将会使用
# Go语言基础库net/http中的DefaultMaxIdleConnsPerHost。
# 如果造成 'too many open files' 错误，你也可以增加这个值或改变 `ulimit`。
#
# 可选
# 默认: 200
#
# MaxIdleConnsPerHost = 200

# 如果设置为 true, 无效的 SSL 证书也会被后端所接受。If set to true invalid SSL certificates are accepted for backends.
# 注意：这会禁用中间人攻击（man-in-the-middle attacks）监测，所以只能被用在安全的后端网络中。
#
# 可选
# 默认: false
#
# InsecureSkipVerify = true

# 被前端所使用的入口点未指定任何入口点。
# 任何前端可以指定它自己的入口点。
#
# 可选
# 默认: ["http"]
#
# defaultEntryPoints = ["http", "https"]
[web]
address = ":8088"


[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    # [entryPoints.http.redirect]
    # entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "cert/www.coe.com.crt"
      keyFile = "cert/www.coe.com.key"

[file]
  [backends]
    [backends.backend1]
      [backends.backend1.LoadBalancer]
        method = "drr"
      [backends.backend1.servers.server1]
      url = "http://127.0.0.1:4040"
      weight = 1
      [backends.backend1.servers.server2]
      url = "http://127.0.0.1:4041"
      weight = 1

  [frontends]
    [frontends.frontend1]
    backend = "backend1"
      # [frontends.frontend1.routes.test_1]
      # rule = "Host:www.coe.com"

